sudo: required

services:
  - docker

git:
  submodules: false

script:
  - GALAXY_USER=galaxy GALAXY_CONTAINER=bgruening/galaxy-stable:latest ./run-container.sh
  - sleep 15
  - docker logs galaxytest
  - docker exec -ti galaxytest ps auxf
  - docker exec -ti galaxytest ps auxf | awk '{print $1}' | sort | uniq | grep -v USER > actual.txt
  - diff -u actual.txt expected.txt
